### ISSUE TITLE
NPS timeperiod?

### ISSUE THREAD

**Issue by dovy** [sponno/asknicely#1]
I'd love to grab the NPS for a time-period, but your documentation is lacking. How do I say pull the NPS for the last 7 days?

asknice.ly/api/v1/getnps/days works fine, but changing days to anything else won't do a thing.

**Comment by sponno** [comment]
Hi Dave

Just add the days on the end. Eg /30 for 30 days.
asknice.ly/api/v1/getnps/days/30 http://asknice.ly/api/v1/getnps/days/30 

Cheers, John.

**Comment by dovy** [comment]
Of course, haha. Thanks.
